# Generated by Django 5.0 on 2023-12-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0002_alter_person_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
