# Generated by Django 5.0 on 2023-12-08 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0003_alter_person_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="name",
            new_name="department_name",
        ),
    ]
